# This workflow will build a golang project
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Test
      run: go test -v ./...

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o build/linux/encdec
        GOOS=windows GOARCH=amd64 go build -v -o build/windows/encdec.exe
        GOOS=darwin GOARCH=amd64 go build -v -o build/macos/intel/encdec
        GOOS=darwin GOARCH=ard64 go build -v -o build/macos/silicon/encdec


